OrdererOrgs:
  - Name: Orderer
    Domain: orderer.recordweb.dev
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: RecordWebOrg
    Domain: org.recordweb.dev
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: SwissGovOrg
    Domain: swissgov.recordweb.dev
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1